### ISSUE TITLE
License and availability to end users

### ISSUE THREAD

**Issue by IzzySoft** [jonathanklee/Sapio#1]
This looks like a promising app, thanks for providing it! However: you didn't declare any license, so the code is "all rights reserved" – which leads to juristical uncertainties. Mind choosing a FOSS license? [SPDX](https://spdx.org/licenses/) might help you picking one – ideally one approved by OSI and FSF.

Further: end-users won't be able to self-compile. How about providing an APK (attached to your tags/releases)? Or, given you've chosen a FOSS license, maybe bringing the app to [F-Droid](https://f-droid.org/) so they build and provide the APK with even improved trust (F-Droid performs quite some tests to make sure the app is FOSS and doesn't come with some "surprises", so users trust it more than downloading from some website)?

**Comment by jonathanklee** [comment]
@IzzySoft Hello. Thank you for your feedback. I added a License file as you mentioned. 

Regarding publishing it to F-droid, I already tried and noticed that the Parse sdk I use for the backend pulls a dependency on Google Firebase for some random unrelated feature I guess. F-droid detects this dependency on Firebase and refuses to build so I might need to move to another backend if I want to publish it to F-droid. 

Sapio has another dependency on Google because I use Google SafetyNet to prevent people who have a Google certified device to evaluate an application. I might need to find another way to filter out those devices too I want to publish Sapio to F-droid.

**Comment by IzzySoft** [comment]
> I added a License file as you mentioned.

Great, thanks! Good choice :smiley:

> I already tried and noticed that the Parse sdk I use for the backend pulls a dependency on Google Firebase

Oh? As you don't provide an APK I cannot cross-check. Would you mind attaching a signed (release-)APK to the corresponding tag/release? I could then check and, if it's acceptable (i.e. meets the inclusion criteria), add your app to [my repo](https://apt.izzysoft.de/fdroid) until you can "move over" (hundreds of apps already went that way, and many other hundreds simply stayed with my repo – it's currently the second largest F-Droid repo available with almost 900 apps, only F-Droid.org itself has more (by factor 4)).

> I use Google SafetyNet to prevent people who have a Google certified device to evaluate an application.

This part I do not understand. You want to prevent users with devices that pass SafetyNet from using the app? What's the reasoning behind that? They might wish to go Google-free but first make sure the apps they use will still run on "that" custom ROM with no Google Services, for example. I thought that was the idea behind your app?

**Comment by jonathanklee** [comment]
@IzzySoft Actually, everyone can see the evaluations of application. Sapio just restricts the contribution part to people who don't have a certified Google device so that they don't contribute with false positive values. 
I will provide you a signed apk so that you can have a look.

**Comment by jonathanklee** [comment]
@IzzySoft You can find the signed apk here: https://github.com/jonathanklee/Sapio/releases/tag/v0.2

**Comment by IzzySoft** [comment]
> Sapio just restricts the contribution part to people who don't have a certified Google device so that they don't contribute with false positive values.

Ah, now I understand – and even can make sense of that screenshot (with the `migrog` labels) :smile:

> You can find the signed apk here

Let's take a look… aww, that looks really bad: 11 offending libs, that's not even eligible for my repo :cry:

```
Offending libs:
---------------
* Play Install Referrer Library (/com/android/installreferrer): NonFreeDep,NonFreeNet,Tracking
* Facebook SDK for Android (/com/facebook): NonFreeDep,Tracking
* Facebook Analytics (/com/facebook/appevents): Tracking
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Android Market (/com/google/android/finsky): NonFreeNet
* Google Cloud Messaging (/com/google/android/gms/cloudmessaging): NonFreeDep,NonFreeNet
* Play Services SafetyNet (/com/google/android/gms/safetynet): NonFreeDep,NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* Firebase Analytics (/com/google/firebase/analytics): NonFreeDep,Tracking
* Firebase Installations (/com/google/firebase/installations): NonFreeNet

11 offenders.
```

Educated guess: SafetyNet drags in GMS & Firebase, and you didn't explicitly opt out of Firebase Analytics. That would explain half of it – though not the install referrer, Facebook SDK and Facebook Analytics (big ouch to those two!! That's really, really bad for privacy) and market.

<details><summary>full list</summary><pre><code>Libraries detected:
-------------------
* Android Support v4 (/android/support/v4): Development Framework, Apache-2.0
* AndroidX Activity (/androidx/activity): Utility, Apache-2.0
* Android Jetpack Annotations (/androidx/annotation): Utility, Apache-2.0
* Arch (/androidx/arch): Utility, Apache-2.0
* AppCompat (/androidx/appcompat): Utility, Apache-2.0
* Asynclayoutinflater (/androidx/asynclayoutinflater): UI Component, Apache-2.0
* Browser (/androidx/browser): Utility, Apache-2.0
* Cardview (/androidx/cardview): UI Component, Apache-2.0
* Android Support Library collections (/androidx/collection): Utility, Apache-2.0
* Concurrent (/androidx/concurrent): Utility, Apache-2.0
* Constraint Layout Library (/androidx/constraintlayout): Utility, Apache-2.0
* Coordinatorlayout (/androidx/coordinatorlayout): UI Component, Apache-2.0
* Androidx Core (/androidx/core): Utility, Apache-2.0
* AndroidX Cursor Adapter (/androidx/cursoradapter): Utility, Apache-2.0
* Android Support Library Custom View (/androidx/customview): UI Component, Apache-2.0
* Documentfile (/androidx/documentfile): UI Component, Apache-2.0
* Drawerlayout (/androidx/drawerlayout): UI Component, Apache-2.0
* Dynamicanimation (/androidx/dynamicanimation): UI Component, Apache-2.0
* Android Emoji2 Compat (/androidx/emoji2): UI Component, Apache-2.0
* Exifinterface (/androidx/exifinterface): Utility, Apache-2.0
* AndroidX Fragment (/androidx/fragment): UI Component, Apache-2.0
* Interpolator (/androidx/interpolator): UI Component, Apache-2.0
* androidx.legacy (/androidx/legacy): Utility, Apache-2.0
* Lifecycle (/androidx/lifecycle): Utility, Apache-2.0
* Loader (/androidx/loader): Utility, Apache-2.0
* AndroidX Local Broadcast Manager (/androidx/localbroadcastmanager): Utility, Apache-2.0
* Media (/androidx/media): Utility, Apache-2.0
* Navigation (/androidx/navigation): Utility, Apache-2.0
* Print (/androidx/print): Utility, Apache-2.0
* ResourceInspection (/androidx/resourceinspection): Development Aid, Apache-2.0
* Recyclerview (/androidx/recyclerview): Utility, Apache-2.0
* Android Activity Saved State (/androidx/savedstate): Utility, Apache-2.0
* Slidingpanelayout (/androidx/slidingpanelayout): UI Component, Apache-2.0
* Startup (/androidx/startup): Utility, Apache-2.0
* Swiperefreshlayout (/androidx/swiperefreshlayout): UI Component, Apache-2.0
* AndroidX Test (/androidx/test): Development Framework, Apache-2.0
* Tracing (/androidx/tracing): Utility, Apache-2.0
* Transition (/androidx/transition): UI Component, Apache-2.0
* Vectordrawable (/androidx/vectordrawable): UI Component, Apache-2.0
* Android Jetpack VersionedParcelable (/androidx/versionedparcelable): Utility, Apache-2.0
* Viewpager (/androidx/viewpager): UI Component, Apache-2.0
* AndroidX Widget ViewPager2 (/androidx/viewpager2): UI Component, Apache-2.0
* Jetpack WindowManager Library (/androidx/window): Utility, Apache-2.0
* Play Install Referrer Library (/com/android/installreferrer): Utility, Proprietary; NonFreeDep,NonFreeNet,Tracking
* Glide (/com/bumptech/glide): Utility, BSD-2-Clause
* Facebook SDK for Android (/com/facebook): Social Network, Proprietary; NonFreeDep,Tracking
* Facebook Analytics (/com/facebook/appevents): Mobile Analytics, Proprietary; Tracking
* Firebase Data Transport (/com/google/android/datatransport): Utility, Apache-2.0; NonFreeNet
* Android Market (/com/google/android/finsky): App Market, LicenseUnknown; NonFreeNet
* Google Cloud Messaging (/com/google/android/gms/cloudmessaging): Utility, Proprietary; NonFreeDep,NonFreeNet
* Play Services SafetyNet (/com/google/android/gms/safetynet): Utility, Proprietary; NonFreeDep,NonFreeNet
* Google Mobile Services (/com/google/android/gms): Development Framework, Proprietary; NonFreeDep
* Google Material Design (/com/google/android/material): Utility, Apache-2.0
* Google Core Libraries for Java 6+ (/com/google/common): Utility, Apache-2.0
* Firebase (/com/google/firebase): Utility, LicenseUnknown; NonFreeNet,NonFreeDep
* Firebase Analytics (/com/google/firebase/analytics): Mobile Analytics, Proprietary; NonFreeDep,Tracking
* Firebase Installations (/com/google/firebase/installations): Development Aid, Apache-2.0; NonFreeNet
* gdata-java-client (/com/google/gdata): Utility, Apache-2.0
* ZXing ('Zebra Crossing') (/com/google/zxing): Utility, Apache-2.0
* Nimbus JOSE+JWT (/com/nimbusds/jose): Utility, Apache-2.0
* Parse.com (/com/parse): Development Framework, BSD-3-Clause
* RootBeer (/com/scottyab/rootbeer): Utility, Apache-2.0
* OkHttp (/com/squareup/okhttp): Utility, Apache-2.0
* Dagger (/dagger): Utility, Apache-2.0
* RxJava (/io/reactivex): Utility, Apache-2.0
* JavaX Annotation API (/javax/annotation): Utility, BSD-3-Clause
* JavaX Dependency Injection (/javax/inject): Utility, Apache-2.0
* Junit (/junit): Utility, EPL-1.0
* Kotlin (/kotlin): Utility, Apache-2.0
* Kotlin Android Extensions Runtime (/kotlinx/android/extensions-runtime): Utility, Apache-2.0
* kotlinx.coroutines (/kotlinx/coroutines): Utility, Apache-2.0
* JCIP Annotations (/net/jcip/annotations): Utility, Apache-2.0
* json-smart-v2 (/net/minidev/json): Utility, Apache-2.0
* Signpost Oauth (/oauth/signpost): Utility, Apache-2.0
* OkHttp okio Framework (/okio): Utility, Apache-2.0
* Apache Commons (/org/apache/commons): Development Framework, Apache-2.0
* Java Hamcrest (/org/hamcrest): Utility, BSD-3-Clause
* IntelliJ IDEA (/org/intellij): Utility, Apache-2.0
* jUnit Java Unit Test (/org/junit): Utility, EPL-2.0
* ASM (/org/objectweb/asm): Utility, BSD-3-Clause
* Reactive Streams (/org/reactivestreams): Utility, MIT
* okhttp-signpost (/se/akerfeldt/okhttp/signpost): Utility, Apache-2.0
 
Offending libs:
---------------
* Play Install Referrer Library (/com/android/installreferrer): NonFreeDep,NonFreeNet,Tracking
* Facebook SDK for Android (/com/facebook): NonFreeDep,Tracking
* Facebook Analytics (/com/facebook/appevents): Tracking
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Android Market (/com/google/android/finsky): NonFreeNet
* Google Cloud Messaging (/com/google/android/gms/cloudmessaging): NonFreeDep,NonFreeNet
* Play Services SafetyNet (/com/google/android/gms/safetynet): NonFreeDep,NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* Firebase Analytics (/com/google/firebase/analytics): NonFreeDep,Tracking
* Firebase Installations (/com/google/firebase/installations): NonFreeNet
 
11 offenders.</code></pre></details>

**Comment by jonathanklee** [comment]
@IzzySoft I told you (: Still some work to do.

**Comment by IzzySoft** [comment]
Yeah, so you id. This wasn't intended as accusation but rather as a hint what the scanner is finding (the above output is by my scanner, which is used by F-Droid's IsueBot as well in RFP and Merge Requests, so it's a good indicator. It just scans the APK, though – so even though it might report "all fine", its counter-part scanning the sources might complain about different things like blobs etc).

I keep my fingers crossed then :crossed_fingers: and wish you good progress! Should you need another scan to see how far you got, just let me know (you can of course also run the scan yourself, the script is FOSS – see e.g. [Identify modules in apps](https://android.izzysoft.de/articles/named/app-modules-2)).

**Comment by IzzySoft** [comment]
Thanks! The license is there, but no APKs anymore?

**Comment by jonathanklee** [comment]
@IzzySoft My merge request has been approved on f-droid. People can build them on their own otherwise.

**Comment by IzzySoft** [comment]
Oh – yes, that slipped at my end, apologies. Thought I saw it somewhere, should have checked :see_no_evil: Thanks!

**Comment by jonathanklee** [comment]
@IzzySoft No worries (:

**Comment by IzzySoft** [comment]
Yeah, it's not yet live in the index so I didn't see it there. But it will be soon, one of the next build cycles hopefully will have it. Thanks!
