### ISSUE TITLE
Add a Themed Icon

### ISSUE THREAD

**Issue by Darkempire78** [jonathanklee/Sapio#10]
Add a themed icon to follow the Material You theme

**Comment by sebastien46** [comment]
@jonathanklee can I work on this?
If so, could you send me the source vector? bitmap tracing is sketchy

**Comment by jonathanklee** [comment]
@sebastien46 Hi. Thank you for suggesting. I credited the icon in the README actually: https://www.flaticon.com/free-icon/brain_4251899?term=brain&page=1&position=35&origin=tag&related_id=4251899
