### ISSUE TITLE
Adding a warning/advice to report, preferably, apps actually dependent on play services

### ISSUE THREAD

**Issue by darhma** [jonathanklee/Sapio#12]
I find the app very useful and well done, however I notice that many reports are for apps in the official f-droid repo and this isn't very useful as apps in the official f-droid repo don't have play services dependencies and should all work without problems, the main utility of the app is to keep track of the compatibility of apps that require play services, to avoid "useless" reports I think a warning could be put up to clarify this point (obviously without "banning" "useless" reports, but simply to make users better understand how f-droid works and which reports are actually useful), It would suffice to add a further explanation of a couple of lines to the "contribute" page.

**Comment by jonathanklee** [comment]
@darhma I agree. I will add a paragraph in the warning regarding f-droid apps. Thank you for your feedback!

**Comment by jonathanklee** [comment]
@darhma Done!
