### ISSUE TITLE
[suggestion] Keep on releasing the apk here on Github

### ISSUE THREAD

**Issue by EdoSecco** [jonathanklee/Sapio#14]
I use [Obtainium](https://github.com/ImranR98/Obtainium) and by chance noticed that you published the apk only until 0.18

Thank you!

**Comment by jonathanklee** [comment]
@EdoSecco I just added the apk for v1.0. Let me know later if fetching from Obtainium worked. I did not know about it actually :+1: Thank you!

**Comment by EdoSecco** [comment]
I tried installing on different phones (with different Android versions) but it fails, both via Obtainium and via the apk downloaded here 🤔

**Comment by jonathanklee** [comment]
@EdoSecco ok I know why. It's probably because it's not signed. Let me upload the debug build.

**Comment by jonathanklee** [comment]
@EdoSecco Sapio_22.apk uploaded.

**Comment by jonathanklee** [comment]
@EdoSecco Nice :+1:
