### ISSUE TITLE
microG not detected

### ISSUE THREAD

**Issue by LuccoJ** [jonathanklee/Sapio#19]
I'm using [LineageOS for microG](https://lineage.microg.org/) 20 on a OnePlus 8T, and Sapio used to detect it as having microG installed (which it does, both in the ROM and as an F-Droid update). Now, with Sapio 1.0.6 from F-Droid, it detects it as "bareAOSP" (and "rooted").

My version of microG is 0.2.29.233013, as updated from the official microg.org repository.

**Comment by jonathanklee** [comment]
@LuccoJ Hi. Thank you for your feedback. Can you download this app, execute it and show me the results ? https://play.google.com/store/apps/details?id=com.scottyab.rootbeer.sample

**Comment by jonathanklee** [comment]
@LuccoJ Issue should be fixed with https://github.com/jonathanklee/Sapio/releases/tag/v1.0.7

**Comment by jonathanklee** [comment]
Should be fixed with 1.0.7
