### ISSUE TITLE
Blocked by Play Protect

### ISSUE THREAD

**Issue by ethanc8** [jonathanklee/Sapio#25]
The installation of versions 1.5.1 and 1.5.2 (and possibly older versions too) is blocked by Play Protect. The dialog doesn't say why.

**Comment by ethanc8** [comment]
![Screenshot_20240718_122822_Google Play Store](https://github.com/user-attachments/assets/68f23416-e000-45e1-ae38-d27a94364fe0)

**Comment by jonathanklee** [comment]
@ethanc8 It's probably because Sapio uses the android.permission.QUERY_ALL_PACKAGES
