### ISSUE TITLE
Thank you, and a couple of questions

### ISSUE THREAD

**Issue by darhma** [jonathanklee/Sapio#3]
Very useful app, thanks! 
I just have a couple of curiosities about how it works: if different experiences are reported about using an app for example using microg and not using it, are they listed separately? And in case there are contradictory reports?

**Comment by jonathanklee** [comment]
Hi @darhma. There are evaluations for each separate device configurations : with microg, without, considered rooted & not considered rooted. I'm currently working on a specific activity that shows the different evaluations for an application. Regarding your second point, only the latest evaluation for a configurations is taken into account.
