### ISSUE TITLE
Non-rooted device detected as rooted

### ISSUE THREAD

**Issue by matphlox** [jonathanklee/Sapio#4]
Hello,
My LineageOS with microG is detected as _rooted_, while it's not. Would it be possible for me to correct that?
Unfortunately, I submitted a report that way about app _PosteID_, today at 14:11 CET. That app works fine on my non-rooted device running microG.
Keep up the good work, thanks

**Comment by jonathanklee** [comment]
Hello. The device is considered rooted by RootBeer. Can you test your device with the RootBeer Sample app ?

**Comment by matphlox** [comment]
Yep, it's detected as rooted by RootBeer Sample app. I'm not an expert at, but I'm pretty sure I just unlocked at the time the bootloader and installed a recovery in order to install the LineageOS with microG ROM.

Two other apps tell me the device is not rooted.

**Comment by jonathanklee** [comment]
@matphlox RootBeer library is the most used one among applications. Can I close the issue if it's fine for you ?

**Comment by matphlox** [comment]
Yes of course, you can close it, it was for your information only

**Comment by jonathanklee** [comment]
@matphlox Thanks for your feedback.
