### ISSUE TITLE
Add a field for "Notifications not working" 

### ISSUE THREAD

**Issue by Booteille** [jonathanklee/Sapio#8]
Hi!

A lot of applications are actually properly working on alternate ROMs except for their notifications, often dependent over Google's Push system.

My proposition is to add a field indicating that only notifications are not working on an app, so we would know that except that, all features are fully working.

**Comment by c-key** [comment]
This would be nice.

**Comment by jonathanklee** [comment]
@Booteille @c-key If notifications are not working, they probably have a dependency towards Google Firebase Cloud Messaging. I would suggest to evaluate those application as "working partially" with a baseAOSP configuration. In a microG configuration, thoses applicationa would be evaluated as "working completely".
